image: $CI_REGISTRY_IMAGE/env:latest

stages:
 - build
 - test
 - report

front-end:
  stage: build
  before_script:
    - ./manage.sh npm_packages
    - ./manage.sh update_dev_packages
  script:
    - ./manage.sh locales
    - ./manage.sh styles
    - ./manage.sh grunt_build

coding-rules:
  stage: build
  before_script:
    - ./manage.sh update_dev_packages
  script:
    - ./manage.sh pep8_check

unit-test:
  stage: test
  before_script:
    - ./manage.sh update_dev_packages
  script:
    - ./manage.sh unit_tests
  artifacts:
    paths:
      - coverage
    expire_in: 1 hour

functional-test:
  stage: test
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  before_script:
    - docker run -id --rm -v $(pwd):/ws -e DOCKER_HOST=tcp://$(cat /etc/hosts | grep docker | cut -f1):2375/ -w /ws --name spotenv $CI_REGISTRY_IMAGE/env:latest sh
    - docker exec -i spotenv ./manage.sh update_dev_packages
  script:
    - docker exec -i spotenv ./manage.sh functional_tests
  artifacts:
    paths:
      - coverage
    expire_in: 1 hour

coverage:
  stage: report
  script:
    - ./manage.sh coverage
  dependencies:
    - unit-test
    - functional-test
  coverage: '/TOTAL.*\s+(\d+%)$/'
