version: '3.6'

services:
  redis:
    restart: unless-stopped
    image: redis:5-alpine

  spot:
    image: ${SPOT_DOCKER_IMG}:${SPOT_DOCKER_TAG}
    restart: unless-stopped
    environment:
      SEARX_REDIS_HOST: redis
      SEARX_LOGGER: INFO

  nginx:
    image: ${SPOT_NGINX_DOCKER_IMG}:${SPOT_NGINX_DOCKER_TAG}
    restart: unless-stopped
