version: '3.6'

x-logging:
  &default-logging
  options:
    max-size: '100m'
    max-file: '3'
  driver: json-file

services:
  redis:
    image: redis:5.0.7-alpine
    container_name: spot-redis
    logging: *default-logging
    restart: unless-stopped
    command: redis-server --maxmemory 8G --maxmemory-policy allkeys-lru

  spot:
    image: registry.gitlab.e.foundation:5000/e/cloud/my-spot:${SPOT_DOCKER_TAG}
    container_name: spot-spot
    build:
      context: .
      dockerfile: Dockerfile
    logging: *default-logging
    restart: unless-stopped
    environment:
      SEARX_SECRET: "${SEARX_SECRET}"
      SEARX_MORTY_URL: "${SEARX_MORTY_URL}"
      SEARX_MORTY_KEY: "${SEARX_MORTY_KEY}"
      SEARX_PROXY_HTTP: "${SEARX_PROXY_HTTP}"
      SEARX_PROXY_HTTPS: "${SEARX_PROXY_HTTPS}"
      SEARX_REDIS_HOST: "${SEARX_REDIS_HOST}"
      SEARX_UI_DEFAULT_THEME: "${SEARX_UI_DEFAULT_THEME}"
      GUNICORN_LOGGER: 1
      GUNICORN_LEVEL: INFO

  spot-nginx:
    image: registry.gitlab.e.foundation:5000/e/cloud/my-spot/nginx:${SPOT_NGINX_DOCKER_TAG}
    container_name: spot-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    logging: *default-logging
    restart: unless-stopped
    environment:
      SEARX_MORTY_URL: "${SEARX_MORTY_URL}"

  filtron:
    image: dalf/filtron:latest
    container_name: spot-filtron
    logging: *default-logging
    restart: unless-stopped
    command: -listen :3000 -rules /etc/filtron/rules.json -target spot-nginx
    networks:
      - spot-wireguarded
    ports:
      - ${WIREGUARD_IP}:8088:3000
    volumes:
      - ${REPO_BASE}/etc/filtron/rules.json:/etc/filtron/rules.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filtron.rule=Host(`${SPOT_HOSTNAME}`)"

  morty:
    image: dalf/morty:latest
    container_name: spot-morty
    logging: *default-logging
    restart: unless-stopped
    networks:
      - spot-wireguarded
    ports:
      - ${WIREGUARD_IP}:8089:3000
    environment:
      DEBUG: "false"
      MORTY_ADDRESS: ":3000"
      MORTY_KEY: "${SEARX_MORTY_KEY}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.morty.rule=Host(`${SPOT_MORTY_HOSTNAME}`)"

  tor:
    image: osminogin/tor-simple
    #container_name: spot-tor
    logging: *default-logging
    restart: unless-stopped
    

networks:
  spot-wireguarded:
    external: true