version: '3.6'

x-logging:
  &default-logging
  options:
    max-size: '1g'
    max-file: '5'
  driver: json-file

services:
  spot:
    image: ${SPOT_DOCKER_IMG}:${SPOT_DOCKER_TAG}
    logging: *default-logging
    restart: unless-stopped
    environment:
      SEARX_SECRET: ":@)%NN0+OqNdy:{prWQlZ{p9|oO9p-UyJq@%V!~G:arrSx6fXz.{jd%=XF44ncj"
      SEARX_MORTY_URL: "${SPOT_MORTY_URL}"
      SEARX_MORTY_KEY: "${SEARX_MORTY_KEY:-KHN0ZGluKT0gNWNmNzQ0Y2JlNjI4MDRjODAwZGUyMGY5ZjZlZTFmZWI1NTg2YTg5OAo=}"
      GUNICORN_LOGGER: 1
      GUNICORN_LEVEL: INFO

  nginx:
    image: ${SPOT_NGINX_DOCKER_IMG}:${SPOT_NGINX_DOCKER_TAG}
    logging: *default-logging
    restart: unless-stopped
    environment:
      SPOT_MORTY_URL: "${SPOT_MORTY_URL}"

  filtron:
    image: ${SPOT_FILTRON_DOCKER_IMG}:${SPOT_FILTRON_DOCKER_TAG}
    logging: *default-logging
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spot.rule=Host(`${SPOT_HOSTNAME}`)"
      - "traefik.http.routers.spot.entrypoints=websecure"
      - "traefik.http.routers.spot.tls.certresolver=spotchallenge"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  morty:
    image: ${SPOT_MORTY_DOCKER_IMG}:${SPOT_MORTY_DOCKER_TAG}
    logging: *default-logging
    restart: unless-stopped
    environment:
      SEARX_MORTY_KEY: "${SEARX_MORTY_KEY:-KHN0ZGluKT0gNWNmNzQ0Y2JlNjI4MDRjODAwZGUyMGY5ZjZlZTFmZWI1NTg2YTg5OAo=}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spot_proxy.rule=Host(`${SPOT_MORTY_HOSTNAME}`)"
      - "traefik.http.routers.spot_proxy.entrypoints=websecure"
      - "traefik.http.routers.spot_proxy.tls.certresolver=spotchallenge"

  traefik:
    image: "traefik:v2.1.2"
    logging: *default-logging
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.spotchallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.spotchallenge.acme.email=contact@e.email"
      - "--certificatesresolvers.spotchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  letsencrypt:
