version: '3.6'

services:
  redis:
    image: redis:5-alpine

  spot:
    build: .
    environment:
      SEARX_REDIS_HOST: redis
      VIRTUAL_HOST: ${SPOT_HOSTNAME:-spot}
      LETSENCRYPT_HOST: ${SPOT_HOSTNAME:-spot}
      SEARX_LOGGER: INFO
