version: '3.6'

x-logging:
  &default-logging
  options:
    max-size: '100m'
    max-file: '3'
  driver: json-file

services:
  redis:
    image: redis:5.0.7-alpine
    logging: *default-logging
    restart: unless-stopped
    command: redis-server --maxmemory 8G --maxmemory-policy allkeys-lru

  spot:
    image: registry.gitlab.e.foundation:5000/e/cloud/my-spot:${SPOT_DOCKER_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    logging: *default-logging
    restart: unless-stopped
    environment:
      SEARX_SECRET: "${SPOT_SECRET}"
      SEARX_MORTY_URL: "${SPOT_MORTY_URL}"
      SEARX_MORTY_KEY: "${MORTY_KEY}"
      SEARX_PROXY_HTTP: "socks5://tor:9050"
      SEARX_PROXY_HTTPS: "socks5://tor:9050"
      SEARX_REDIS_HOST: "redis"
      SEARX_UI_DEFAULT_THEME: "eelo"
      GUNICORN_LOGGER: 1
      GUNICORN_LEVEL: INFO

  nginx:
    image: registry.gitlab.e.foundation:5000/e/cloud/my-spot/nginx:${SPOT_NGINX_DOCKER_TAG}
    build:
      context: .
      dockerfile: nginx.Dockerfile
    logging: *default-logging
    restart: unless-stopped
    environment:
      SPOT_MORTY_URL: "${SPOT_MORTY_URL}"

  filtron:
    image: dalf/filtron:latest
    logging: *default-logging
    restart: unless-stopped
    command: -listen :3000 -rules /etc/filtron/rules.json -target nginx
    ports:
      - "8088:3000"
    volumes:
      - ./etc/filtron/rules.json:/etc/filtron/rules.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filtron.rule=Host(`${SPOT_HOSTNAME}`)"

  morty:
    image: dalf/morty:latest
    logging: *default-logging
    restart: unless-stopped
    ports:
      - "8089:3000"
    environment:
      DEBUG: "false"
      MORTY_ADDRESS: ":3000"
      MORTY_KEY: "${MORTY_KEY}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.morty.rule=Host(`${SPOT_MORTY_HOSTNAME}`)"

  tor:
    image: osminogin/tor-simple
    logging: *default-logging
    restart: unless-stopped
